[package]
name = "atarvi-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27"
rand = "0.8" # For randomizing the game grid
ascii = { version = "1.1", default-features = false }
itoa = "1.0.14"
